VERSION=	9.3.25
REVISION=	0

SHARED_LIBS=	ecpg		7.5 \
		ecpg_compat	4.5 \
		pgtypes		4.4 \
		pq		6.6

pre-build:
	${PRE_BUILD}

post-build:
	${POST_BUILD}

post-install:
	${POST_INSTALL}

.include <bsd.port.mk>
