VERSION=	9.2.24
REVISION=	0

SHARED_LIBS=	ecpg		7.4 \
		ecpg_compat	4.4 \
		pgtypes		4.3 \
		pq		6.5

pre-build:
	${PRE_BUILD}

post-build:
	${POST_BUILD}

post-install:
	${POST_INSTALL}

.include <bsd.port.mk>
