VERSION=	9.5.5
REVISION=	4

SHARED_LIBS=	ecpg		7.7 \
		ecpg_compat	4.7 \
		pgtypes		4.6 \
		pq		6.8

pre-build:
	${PRE_BUILD}

post-build:
	${POST_BUILD}

post-install:
	${POST_INSTALL}

.include <bsd.port.mk>
